#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config height             38
spacebar -m config spacing_left       25
spacebar -m config spacing_right      30
spacebar -m config text_font         "DankMono Nerd Font Mono:Regular:18.0"
spacebar -m config icon_font         "DankMono Nerd Font Mono:Regular:22.0"

spacebar -m config background_color     0xff282828
spacebar -m config foreground_color     0xffebdbb2
spacebar -m config space_icon_color     0xfffb4934
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xff83a598
spacebar -m config clock_icon_color     0xffebdbb2
#spacebar -m config space_icon_strip   "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X"

spacebar -m config space_icon_strip "一" "二" "三" "四" "五" "六" "七" "八" "九" "十"

spacebar -m config spaces_for_all_displays  "on"
spacebar -m config display_separator          "on"
spacebar -m config display_separator_icon     " "

#spacebar -m config padding_left       20
#spacebar -m config padding_right      20

spacebar -m config power_icon_strip   ⚡ ⚡
spacebar -m config space_icon         ""
spacebar -m config clock_icon         🕛
spacebar -m config dnd_icon           ""
spacebar -m config clock_format       "%d/%m/%y %I:%M"
#spacebar -m config right_shell on
#spacebar -m config right_shell_icon   ""
#spacebar -m config right_shell_command "~/bin/cpu-temp.sh"

#spacebar -m config title            "off"
#spacebar -m config center_shell on
#spacebar -m config center_shell_command "~/bin/spotify_mini/bar_sptmini.sh"

echo "spacebar configuration loaded.."
